apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-demo
  namespace: destination
spec:
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: destination-kafka-rest
      namespace: destination
  sourceKafkaCluster:
    bootstrapEndpoint: kafka.source.svc.cluster.local:9071
    authentication:
      type: mtls
    tls:
      enabled: true
      secretRef: source-tls-secret
    kafkaRestClassRef:
      name: source-kafka-rest
      namespace: destination
  mirrorTopics:
  - name: demo
