---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-hdfs
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  kafkaClusterRef:
    name: kafka
    namespace: confluent
