apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: confluent-operator
rules:
# The cluster.confluent.com and operator.confluent.cloud rules only needed when migrating from operator 1.x
- apiGroups:
  - cluster.confluent.com
  resources:
  - zookeeperclusters
  - zookeeperclusters/status
  - zookeeperclusters/scale
  - zookeeperclusters/finalizers
  - kafkaclusters
  - kafkaclusters/status
  - kafkaclusters/scale
  - kafkaclusters/finalizers
  verbs:
  - '*'
- apiGroups:
  - operator.confluent.cloud
  resources:
  - physicalstatefulclusters
  - physicalstatefulclusters/scale
  - physicalstatefulclusters/status
  - physicalstatefulclusters/finalizers
  verbs:
  - '*'
- apiGroups:
  - platform.confluent.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# The route.openshift.io rule only needed when deploying on Openshift
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - secrets
  - secrets/finalizers
  - pods
  - pods/exec # This is only required with CFK 2.0.0, CFK 2.0.1+ does not require this
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list # needed for nonnamespaced deployments
  - watch # needed for nonnamespaced deployments
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: confluent-operator
subjects:
- kind: ServiceAccount
  name: confluent-for-kubernetes # customize as required
  namespace: confluent # customize as required
roleRef:
  kind: ClusterRole
  name: confluent-operator
  apiGroup: rbac.authorization.k8s.io
