apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-cflt-filterandlist
  namespace: destination
spec:
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: destination-kafka-rest
      namespace: destination
  sourceKafkaCluster:
    bootstrapEndpoint: notcflt.destination.svc.cluster.local:9092
    clusterID: XqsWIFY8TcqYbIr_YMxJ2g
  mirrorTopicOptions:
    autoCreateTopics: 
      enabled: true
      topicFilters: 
        - filterType: INCLUDE
          name: nopffilterdemo
          patternType: PREFIXED
  mirrorTopics:
  - name: npfatopic
