apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlinkus-demo
  namespace: destination
spec:
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: destination-kafka-rest
      namespace: destination
  sourceKafkaCluster:
    bootstrapEndpoint: kafka.source.svc.cluster.local:9071
    authentication:
      type: plain
      jaasConfig:
        secretRef: credential
    tls:
      enabled: true
      secretRef: source-tls-group1
    kafkaRestClassRef:
      name: source-kafka-rest
      namespace: source
  mirrorTopics:
  - name: demo
