apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  kubernetes.stretch.server: |
    central.svc.cluster.local:53 {
      errors
      cache 30
      forward . 10.0.16.4
    }
    west.svc.cluster.local:53 {
      errors
      cache 30
      forward . 10.0.32.4
    }