apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-config-ms
data:
  schema: |
    {
      "namespace": "io.confluent.examples.clients.basicavro",
      "type": "record",
      "name": "Payment",
      "fields": [
          {"name": "id", "type": "string"}
      ]
    }
---
apiVersion: apps.cpc.platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: schema-ms
spec:
  data:
    format: avro
    configRef: schema-config-ms
  schemaRegistryClusterRef:
    name: schemaregistry-ms
