apiVersion: v1
kind: Pod
metadata:
  name: pullpod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: pullpod
      image: centos
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/usr/connectordownload"
          name: task-pv-storage