apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: west
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  serviceName: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - command:
            - sleep
            - "3600"
          image: busybox
          name: busybox
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: west
spec:
  clusterIP: None
  ports:
    - name: nc
      port: 5002
      protocol: TCP
      targetPort: 5002
  selector:
    app: busybox