apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-dev
spec:
  replicas: 3
  k8sClusterRef:
    name: data-plane-k8s
    namespace: cpc-system
  blueprintRef:
    name: standard
    namespace: cpc-system
  resourceMetadata:
    overrideName: zookeeper
    overrideNamespace: confluent-dev
---
apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: KafkaCluster
metadata:
  name: kafka-dev
spec:
  replicas: 3
  k8sClusterRef:
    name: data-plane-k8s
    namespace: cpc-system
  blueprintRef:
    name: standard
    namespace: cpc-system
  resourceMetadata:
    overrideName: kafka
    overrideNamespace: confluent-dev
---
apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: SchemaRegistryCluster
metadata:
  name: schemaregistry-dev
spec:
  k8sClusterRef:
    name: data-plane-k8s
    namespace: cpc-system
  blueprintRef:
    name: standard
    namespace: cpc-system
  resourceMetadata:
    overrideName: schemaregistry
    overrideNamespace: confluent-dev
---
apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: ConnectCluster
metadata:
  name: connect-dev
spec:
  k8sClusterRef:
    name: data-plane-k8s
    namespace: cpc-system
  blueprintRef:
    name: standard
    namespace: cpc-system
  resourceMetadata:
    overrideName: connect
    overrideNamespace: confluent-dev
---
apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: KsqlDBCluster
metadata:
  name: ksqldb-dev
spec:
  k8sClusterRef:
    name: data-plane-k8s
    namespace: cpc-system
  blueprintRef:
    name: standard
    namespace: cpc-system
  resourceMetadata:
    overrideName: ksqldb
    overrideNamespace: confluent-dev
---
apiVersion: cluster.cpc.platform.confluent.io/v1beta1
kind: ControlCenterCluster
metadata:
  name: controlcenter-dev
spec:
  k8sClusterRef:
    name: data-plane-k8s
    namespace: cpc-system
  blueprintRef:
    name: standard
    namespace: cpc-system
  resourceMetadata:
    overrideName: controlcenter
    overrideNamespace: confluent-dev
