---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  metricReporter:
    enabled: true
    tls:
      enabled: true
      secretRef: tls-group1
    authentication:
      type: plain
      jaasConfig:
        secretRef: credential
  tls:
    secretRef: tls-group1
  listeners:  
    internal:
      authentication:
        type: ldap
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true  
  authorization:
    type: simple
    superUsers:
    - User:kafka
  identityProvider:
    type: ldap
    ldap:
      address: ldap://ldap.confluent.svc.cluster.local:389
      authentication:
        type: simple
        simple:
          secretRef: credential
      configurations:
        groupNameAttribute: cn
        groupObjectClass: group
        groupMemberAttribute: member
        groupMemberAttributePattern: CN=(.*),DC=test,DC=com
        groupSearchBase: dc=test,dc=com
        userNameAttribute: cn
        userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
        userObjectClass: organizationalRole
        userSearchBase: dc=test,dc=com
# https://docs.confluent.io/operator/current/co-authenticate-kafka.html#configure-ak-for-server-side-sasl-plain-with-ldap-authentication
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  configOverrides:
    log4j: 
      - log4j.rootLogger=DEBUG, stdout
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  authentication:
    type: ldap
    ldap:
      roles: [c3users,readonlyusers]
      restrictedRoles: [readonlyusers]
      property:
        useLdaps : "false"
        debug: "true"
        contextFactory: "com.sun.jndi.ldap.LdapCtxFactory"
        hostname: "ldap.confluent.svc.cluster.local"
        port: "389"
        bindDn: "cn=admin,dc=test,dc=com"
        bindPassword: "confluentrox"
        authenticationMethod: "simple"
        forceBindingLogin: "false"
        userBaseDn: "ou=users,dc=test,dc=com"
        userObjectClass: "inetOrgPerson" 
        userRdnAttribute: "uid"
        userIdAttribute: "cn"
        roleBaseDn: "ou=groups,dc=test,dc=com"
        roleNameAttribute: "cn"
        roleMemberAttribute: "memberUid"
        roleObjectClass: "posixGroup" 
        userPasswordAttribute: "userPassword"
